name: ProjectExplorer
options:
  bundleIdPrefix: com.wilmooreiii
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    GENERATE_INFOPLIST_FILE: YES

targets:
  ProjectExplorer:
    type: application
    platform: iOS
    sources:
      - ProjectExplorer
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.wilmooreiii.projectexplorer
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_CFBundleDisplayName: "Project Explorer"
    info:
      path: ProjectExplorer/Info.plist
      properties:
        CFBundleURLTypes:
          - CFBundleURLName: com.wilmooreiii.projectexplorer
            CFBundleURLSchemes:
              - projectexplorer
    dependencies:
      - target: ProjectExplorerShareExtension
        embed: true

  ProjectExplorerShareExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: ProjectExplorerShareExtension
        excludes:
          - Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.wilmooreiii.projectexplorer.ShareExtension
        INFOPLIST_FILE: ProjectExplorerShareExtension/Info.plist
        SKIP_INSTALL: YES
